"""ROM version profiles.

A profile describes the differences between ROM revisions/regions that the
randomizer needs to know about: patch address mapping, pointer table layout,
code symbols and language. The English reference ROM uses an identity profile
so behaviour is unchanged; the French ROM uses a profile generated by the
Phase A tooling (``rommap_fr.json``).
"""
from __future__ import annotations

import hashlib
import json
import os
from typing import Any, Dict, Optional, Set

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
ROMMAP_FR = os.path.join(REPO_ROOT, "rommap_fr.json")

EN_SHA1 = "d90ac17e9bf17b6c61624ad9f05447bdb5efc01a"
FR_SHA1 = "b5e4df1a67432c609fa0f23519315297c6dcdc1d"

# LADXR scratch banks: addresses are defined by the randomizer itself.
SCRATCH_BANKS = {0x3E, 0x3F}


class UnmappedPatchError(Exception):
    pass


class RomProfile:
    def __init__(
        self,
        name: str,
        *,
        language: str = "en",
        patch_map: Optional[Dict[Any, int]] = None,
        identical_banks: Optional[Set[int]] = None,
        tables: Optional[Dict[str, Any]] = None,
        symbols: Optional[Dict[str, int]] = None,
        code_addrs: Optional[Dict[Any, int]] = None,
        verify_patches: bool = True,
        strict: bool = False,
    ) -> None:
        self.name = name
        self.language = language
        self.patch_map = patch_map or {}
        self.identical_banks = identical_banks or set()
        self.tables = tables or {}
        self.symbols = symbols or {}
        self.code_addrs = code_addrs or {}
        self.verify_patches = verify_patches
        self.strict = strict
        # Diagnostics filled during translation.
        self.code_operands_translated = 0
        self.code_operands_unmapped = 0
        self.code_unmapped_operands: Set[Any] = set()

    @property
    def is_identity(self) -> bool:
        return self.name == "en"

    def translate_patch(self, bank: int, addr: int) -> Optional[int]:
        if self.is_identity:
            return addr
        mapped = self.patch_map.get((bank, addr))
        if mapped is not None:
            return mapped
        if bank in self.identical_banks or bank in SCRATCH_BANKS:
            return addr
        return None

    def translate_code_addr(self, bank: int, addr: int) -> Optional[int]:
        if self.is_identity:
            return addr
        if bank in self.identical_banks or bank in SCRATCH_BANKS:
            return addr
        mapped = self.code_addrs.get((bank, addr))
        if mapped is not None:
            return mapped
        mapped = self.patch_map.get((bank, addr))
        if mapped is not None:
            return mapped
        return None

    def translate_code_bytes(self, bank: int, raw: bytes) -> bytes:
        """Translate absolute 16-bit operands in assembled code."""
        if self.is_identity or bank in self.identical_banks or bank in SCRATCH_BANKS:
            return raw
        from codebytes import iter_abs16_operands

        out = bytearray(raw)
        for index, operand in iter_abs16_operands(raw):
            if operand < 0x4000:
                target_bank = 0
            elif operand < 0x8000:
                target_bank = bank
            else:
                continue
            translated = self.translate_code_addr(target_bank, operand)
            if translated is not None:
                out[index + 1] = translated & 0xFF
                out[index + 2] = (translated >> 8) & 0xFF
                self.code_operands_translated += 1
            else:
                self.code_operands_unmapped += 1
                self.code_unmapped_operands.add((target_bank, operand))
        return bytes(out)

    def table_config(self, name: str) -> Optional[Dict[str, Any]]:
        if self.is_identity:
            return None
        return self.tables.get(name)

    def symbol_overrides(self) -> Dict[str, int]:
        return dict(self.symbols)

    def __repr__(self) -> str:
        return "RomProfile(%s, patches=%d, code=%d, tables=%d, symbols=%d)" % (
            self.name,
            len(self.patch_map),
            len(self.code_addrs),
            len(self.tables),
            len(self.symbols),
        )


EN_PROFILE = RomProfile("en", language="en")

_FR_CACHE: Optional[RomProfile] = None


def _load_fr_profile() -> RomProfile:
    global _FR_CACHE
    if _FR_CACHE is not None:
        return _FR_CACHE
    if not os.path.exists(ROMMAP_FR):
        raise FileNotFoundError(
            "French profile requested but %s is missing. Run tools/relocate.py first." % ROMMAP_FR
        )
    with open(ROMMAP_FR, "rt", encoding="utf-8") as f:
        data = json.load(f)

    patch_map: Dict[Any, int] = {}
    for entry in data.get("patches", []):
        if entry.get("fr_addr") is None or entry.get("bank") is None or entry.get("en_addr") is None:
            continue
        patch_map[(entry["bank"], entry["en_addr"])] = entry["fr_addr"]

    identical = {int(b, 16) for b in data.get("identical_banks", [])}

    tables = data.get("tables", {}).get("config", {})

    symbols: Dict[str, int] = {}
    for name, entry in data.get("symbols", {}).get("labels", {}).items():
        fr = entry.get("fr")
        if fr is not None and fr != entry.get("en"):
            symbols[name.upper()] = fr

    code_addrs: Dict[Any, int] = {}
    for key, entry in data.get("code_addrs", {}).get("addrs", {}).items():
        fr = entry.get("fr")
        if fr is None:
            continue
        bank_str, addr_str = key.split(":")
        code_addrs[(int(bank_str, 16), int(addr_str, 16))] = fr

    _FR_CACHE = RomProfile(
        "fr",
        language="fr",
        patch_map=patch_map,
        identical_banks=identical,
        tables=tables,
        symbols=symbols,
        code_addrs=code_addrs,
        verify_patches=False,
        strict=False,
    )
    return _FR_CACHE


def detect_profile(rom_bytes: bytes) -> RomProfile:
    sha = hashlib.sha1(rom_bytes).hexdigest()
    if sha == EN_SHA1:
        return EN_PROFILE
    if sha == FR_SHA1:
        return _load_fr_profile()
    # Region code lives in the title field at 0x13F..0x142 ("AZLF" for France).
    region = rom_bytes[0x13F:0x143]
    if region != b"\x00\x00\x00\x00":
        try:
            return _load_fr_profile()
        except FileNotFoundError:
            pass
    return EN_PROFILE


def profile_by_name(name: Optional[str]) -> Optional[RomProfile]:
    """Return a profile by name ('en'/'fr'), or None for auto-detection."""
    if name in (None, "", "auto"):
        return None
    if name == "en":
        return EN_PROFILE
    if name == "fr":
        return _load_fr_profile()
    raise ValueError("Unknown ROM profile: %r (expected auto, en or fr)" % (name,))
